accounts/urls.py
from django.urls import path , include
from . import views
urlpatterns = [
    #アカウント管理のパス
    path('',views.Login,name='Login'),
    path("logout",views.Logout,name="Logout"),
    path('register',views.AccountRegistration.as_view(), name='register'),
    path("home",views.home,name="home"),
    path('index',include('daily_report.urls'),name='index'),
]

daily_report/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('index/', views.index, name='index'),#トップページへのリンク
    path('write/', views.write, name='write'),#投稿ページへのリンク
    path('edit/<str:post_id>/',views.edit, name='edit'),
    path('review/<str:post_id>/', views.review, name='review'),
    path('exclude/<str:post_id>/', views.exclude, name='exclude'),
]

project_folder/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('accounts.urls')),
    path('admin/', admin.site.urls),
]

daily_report/models.py
from django.db import models

from django.utils import timezone

import datetime
class Article(models.Model):
    def id_create():
        id_input = str(datetime.datetime.now())
        id_change = id_input.replace(" ","_")
        return id_change
    class Meta(object):
        
        #作成されるテーブル名を指定
        db_table = 'posts'
        #管理画面でのモデルの名称
        verbose_name = '投稿一覧'
    #項目作成
    day = models.DateField('稼働日',blank=True, null=True,max_length=10)
    name = models.CharField('運転者名', max_length=20, blank=True, null=True)
    car_number = models.CharField('車両No', max_length=5, blank=True, null=True)
    weather = models.CharField('天気', max_length=5, blank=True, null=True)
    start = models.TimeField('始業時間',blank=True, null=True,max_length=10)	
    end = models.TimeField('終業時間',blank=True, null=True,max_length=10)
    oiling = models.FloatField('給油',max_length=4,blank=True, null=True)
    oiling2 = models.FloatField('給油',max_length=4,blank=True, null=True)
    oil = models.FloatField('オイル',max_length=4,blank=True, null=True)
    text = models.CharField(verbose_name='備考欄', max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(verbose_name="作成日時",default=timezone.now, blank=True, null=True, max_length=255)
    id = models.CharField(primary_key=True, default=id_create, editable=False, max_length=255)

    def __str__(self):
        
        return str(self.id)

daily_report/forms.py
from django import forms
from .models import Article
from django.core.exceptions import NON_FIELD_ERRORS



class WriteForm(forms.ModelForm):
    class Meta:
        #モデルを指定
        model = Article
        #フォームとして表示したいカラムを指定
        fields = (
            'day',
            'name',
            'car_number',
            'weather',
            'start',
            'end',
            'oiling',
            'oiling2',
            'oil',
            'text'
            )
        widgets = {
            'day': forms.DateInput(
                attrs={
                "type": "date",
                'required' : True
            }),
            'name': forms.TextInput(
                attrs={
                'placeholder': "お名前を入力してください",
                'required' : True
            }),
            'car_number': forms.TextInput(
                attrs={
                'placeholder': "例)88-88",
                'required' : True
            }),
            "start": forms.TimeInput(
                attrs={
                "type": "time",
                'required' : True
            }),
            "end": forms.TimeInput(
                attrs={
                "type": "time",
                'required' : True
            }),
            'weather':forms.Select(
                choices=(
                ('','天気を選択'),
                ('0','晴れ'),
                ('1','曇り'),
                ('2','雨'),
                ('3','雪'),
                ),
                attrs={
                'required' : '天気を選択'
            }),
            'text':forms.Textarea(
                attrs={
                'rows':8, 'cols':30,
                'placeholder': "連絡事項や追加の記入はこちら",
            }),  
        }
        error_messages = {
            'name':{
                'required':"投稿者名が入力されていません",
            },
        }
        
        

daily_report/views.py
from django.shortcuts import render

from daily_report.models import Article

from django.views.generic import View

from django.shortcuts import redirect ,get_object_or_404

from .forms import WriteForm 

# トップページを表示する機能
class IndexView(View):
    def get(self,request):
        # 記録してある投稿の全データを投稿時間を元にソートして表示
        queryset = Article.objects.all().order_by('-created_at')
        # トップページのhtmlへ記録データを乗せ移行
        return render(request, 'daily_report/post.html', {'posts': queryset})

# toppageの表示
index = IndexView.as_view()
# 投稿機能
class WriteView(View):
    # 新規入力画面へ
    def get(self, request):  
        # 投稿ボタンで投稿ページへ
        return render(request, 'daily_report/write.html', {'form': WriteForm})
    # 投稿機能
    def post(self, request):
        # formに書いた内容を格納する
        form = WriteForm(request.POST)
        # 保存する前に一旦取り出す
        post = form.save(commit=False)
        # 保存
        post.save()
        # トップ画面へ
        return redirect(to='index')
    
write = WriteView.as_view()

# 編集処理のクラス
class editView(View):
    # 編集画面を表示するための処理
    def get(self, request, post_id):
        # データベースにある対象のデータのidを一覧から引き受ける(post_id)
        # modelのArticleからid(post_id)を参照して対象のデータを取得
        post = get_object_or_404(Article, pk=post_id)
        # 入力フォームに取得したデータを埋め込んで表示
        edit_form = WriteForm(instance=post)
        # edit.htmlを表示とともに取得したデータと、それを埋め込んだフォームと送る
        return render(request, 'daily_report/edit.html', {'form': edit_form,'post':post})
    # 編集したデータを記録する処理
    def post(self, request, post_id):
        # 編集結果を編集元に反映するためにidを取得
        post = get_object_or_404(Article, pk=post_id)
        # formに書いた内容を編集元へ更新(instance=post)
        form = WriteForm(request.POST, instance=post)
        # 保存する前に一旦取り出す☆後に理解すべし!!!
        post = form.save(commit=False)
        # 保存
        post.save()
        # トップ画面へ
        return redirect(to='index')

edit = editView.as_view()
# 削除機能
def review(request, post_id):
    return render(request, 'daily_report/delete.html',{'post_id':post_id})

#削除の機能
def exclude(request, post_id): 
    # 処理したいデータを指定
    post = get_object_or_404(Article, pk=post_id)
    # 指定のデータ削除
    post.delete()
    # トップ画面へ
    return redirect(to='index')

templates/daily_report/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'daily_report/base.css' %}">
    <title>{% block page_title %}{% endblock %}</title>

</head>
<body>
<nav>
    <p class="site-name">乗務記録</p>
    <ul>
        <li><a href="{% url 'index' %}">Top</a></li>
        <li><a href="{% url 'write' %}">投稿</a></li>
    </ul>
</nav>

<div class="title">
    <h1>{% block title %}{% endblock %}</h1>
</div>

<hr>

<div class="content">
    {% block content%}{% endblock %}
</div>

<hr>

</body>
</html>

templates/daily_report/delete.html
{% extends "daily_report/base.html" %}

{% block page_title %}削除{% endblock %}
{% block title %}削除しますか？{% endblock %}

<button onclick="location.href='{% url 'exclude' post.id %}'">削除</button>

templates/daily_report/edit.html
{% extends "daily_report/base.html" %}

{% block page_title %}編集{% endblock %}
{% block title %}編集{% endblock %}

{% block content %}
    <form method="post" action="{% url 'edit' post.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button">編集</button>
    </form>
{% endblock %}

templates/daily_report/form.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <p>{{ message }}</p>
</body>
</html>

templates/daily_report/post.html
{% extends "daily_report/base.html" %}
{% block page_title %}一覧{% endblock %}
{% block title %}一覧{% endblock %}
{% block content %}
    {% for post in posts %}      
    <div class="post">
        <p class="car_number">{{ post.car_number }}</p>
        <p class="name">{{ post.name }}</p>
        <p class="day">{{ post.day }}</p>
        <hr>
    </div>
    <button onclick="location.href='{% url 'edit' post.id %}'">編集</button>
    <button type="button"  onclick="document.getElementById('{{post.id}}').show();">
        削除
    </button>
    <div class=dialog>
        <dialog id={{post.id}}>
            <h2><span style="font-size:180%;"><font color="#FF6666">削除</font></span>してもよろしいですか？</h2>
            <button onclick="location.href='{% url 'exclude' post.id %}'">
                はい
            </button>
            <button type="button" onclick="document.getElementById('{{post.id}}').close();">
                いいえ
            </button>
        </dialog>
    </div>
    {% endfor %}
{% endblock %}

templates/daily_report/write.html
{% extends "daily_report/base.html" %}

{% block page_title %}投稿{% endblock %}
{% block title %}投稿{% endblock %}

{% block content %}
    <form method="post" action="{% url 'write' %}">
        {% csrf_token %}
        <div id="form" style="">
            <p>
                <label for="id_day">稼働日:</label>
                <input type="date" name="day" required="" id="id_day">
                <span>必須</span>
            </p>
            <p>
                <label for="id_name">運転者名:</label>
                <input type="text" name="name" placeholder="お名前を入力してください" required="" maxlength="20" id="id_name">   
                <span>必須</span>
            </p>
            <p>
                <label for="id_car_number">車両No:</label>
                <input type="text" name="car_number" placeholder="例)88-88" required="" maxlength="5" id="id_car_number">    
                <span>必須</span>
            </p>
            <p>
                <label for="id_weather">天気:</label>
                <select name="weather" required="天気を選択" maxlength="5" id="id_weather">
                    <option value="" selected="">天気を選択</option>

                    <option value="0">晴れ</option>

                    <option value="1">曇り</option>

                    <option value="2">雨</option>

                    <option value="3">雪</option>

                </select>   
                <span>必須</span>             
            </p>
            <p>
                <label for="id_start">始業時間:</label>
                <input type="time" name="start" required="" id="id_start">
                <span>必須</span>                
            </p>            
            <p>
                <label for="id_end">終業時間:</label>
                <input type="time" name="end" required="" id="id_end">
                <span>必須</span>                
            </p>            
            <p>
                <label for="id_oiling">給油:</label>
                <input type="number" name="oiling" step="any" id="id_oiling">                
            </p>            
            <p>
                <label for="id_oiling2">給油:</label>
                <input type="number" name="oiling2" step="any" id="id_oiling2">                
            </p>            
            <p>
                <label for="id_oil">オイル:</label>
                <input type="number" name="oil" step="any" id="id_oil">                
            </p>           
            <p>
                <label for="id_text">備考欄:</label>
                <textarea name="text" cols="30" rows="8" placeholder="連絡事項や追加の記入はこちら" maxlength="255" id="id_text"></textarea>                
            </p>
        </div>
        <button type="submit" class="button">投稿</button>
    </form>
{% endblock %}